#!/bin/sh

#if [ "$1" = "purge" ] ; then
if [ ! -f /bin/systemctl ] ; then
  update-rc.d pf_ring remove >/dev/null
  update-rc.d cluster remove >/dev/null
fi
#fi

/sbin/ldconfig >/dev/null 2>&1

exit 0
