#!/bin/sh

if hash systemctl 2>/dev/null; then
  /bin/systemctl disable pf_ring.service > /dev/null
  /bin/systemctl disable "cluster" > /dev/null
  /bin/systemctl disable "cluster@*" > /dev/null
else
  update-rc.d pf_ring remove > /dev/null
  update-rc.d cluster remove > /dev/null
fi

/sbin/ldconfig >/dev/null 2>&1

exit 0
