#
# Makefile for the Intel(R) 10GbE PCI Express Linux Network Driver
#

obj-m += ixgbevf.o

ixgbevf-objs := ixgbevf_main.o \
	ixgbevf_ethtool.o	\
	ixgbe_vf.o	\
	ixgbe_mbx.o	\
	ixgbe_hv_vf.o	\
	kcompat.o

CFLAGS_ixgbevf_main.o := -I$(src)

EXTRA_CFLAGS += -DHAVE_PF_RING -DIXGBE_NO_HW_RSC -DDISABLE_PACKET_SPLIT
KBUILD_EXTRA_SYMBOLS=${PF_RING_PATH}/kernel/Module.symvers

KVER=$(shell uname -r)

all:
	cd ${PF_RING_PATH}/kernel/; make
	cp ${PF_RING_PATH}/kernel/Module.symvers .
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) clean

