#
# Makefile for the Intel(R) Ethernet Connection Columbiaville (ice.ko) driver
#

obj-m += ice.o

ice-objs := ice_main.o \
	kcompat.o	\
	ice_controlq.o	\
	ice_common.o	\
	ice_nvm.o	\
	ice_switch.o	\
	ice_sched.o	\
	ice_base.o	\
	ice_lib.o	\
	ice_txrx_lib.o	\
	ice_txrx.o	\
	ice_fdir.o	\
	ice_ethtool_fdir.o	\
	ice_acl.o		\
	ice_acl_ctrl.o		\
	ice_flex_pipe.o	\
	ice_flow.o		\
	ice_ethtool.o

CFLAGS_ice_main.o := -I$(src)

EXTRA_CFLAGS += -DHAVE_PF_RING

KVER=$(shell uname -r)

all:
	cd ../../../../../kernel/; make
	cp ../../../../../kernel/Module.symvers .
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) clean

