#
# Makefile for the Intel(R) 10GbE PCI Express Linux Network Driver
#

obj-m += igb.o

igb-objs := igb_main.o \
	kcompat.o	\
	e1000_api.o	\
	igb_ethtool.o	\
	igb_hwmon.o	\
	e1000_mbx.o	\
	e1000_mac.o	\
	e1000_manage.o	\
	e1000_nvm.o	\
	igb_param.o	\
	e1000_phy.o	\
	igb_procfs.o	\
	igb_vmdq.o	\
	e1000_82575.o	\
	e1000_i210.o	\
	igb_ptp.o	\
	igb_debugfs.o

CFLAGS_igb_main.o := -I$(src)

EXTRA_CFLAGS += -DHAVE_PF_RING -DIXGBE_NO_HW_RSC -DDISABLE_PACKET_SPLIT
KBUILD_EXTRA_SYMBOLS=../../../../../kernel/Module.symvers

KVER=$(shell uname -r)

all:
	cd ../../../../../kernel/; make
	cp ../../../../../kernel/Module.symvers .
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) clean

