#
# Makefile for the Intel(R) 1GbE PCI Express Linux Network Driver
#

obj-m += e1000e.o

e1000e-objs := netdev.o \
	ethtool.o	\
	ich8lan.o	\
	mac.o	\
	nvm.o	\
	phy.o	\
	manage.o	\
	80003es2lan.o	\
	82571.o	\
	param.o	\
	ptp.o \
	kcompat.o

CFLAGS_e1000e_main.o := -I$(src)

EXTRA_CFLAGS += -DHAVE_PF_RING -DIXGBE_NO_HW_RSC -DDISABLE_PACKET_SPLIT
KBUILD_EXTRA_SYMBOLS=${PF_RING_PATH}/Module.symvers

KVER=$(shell uname -r)

all:
	cd ${PF_RING_PATH}/; make
	cp ${PF_RING_PATH}/Module.symvers .
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) modules

clean:
	$(MAKE) -C /lib/modules/${KVER}/build M=$(PWD) clean

