
default: install

install:
	cd Endace; ./configure; make install
	#cd Napatech; ./configure; make install
	#cd Netcope; ./configure; make install
clean:
	cd Endace; make clean
	#cd Napatech; make clean
	#cd Netcope; make clean
